ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.IndexView.as_view(), name='ad_list'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create', views.AdCreateView.as_view(success_url=reverse_lazy('ads:ad_list')), name='ad_create'),
    path('ad/<int:pk>/update', views.AdUpdateView.as_view(success_url=reverse_lazy('ads:ad_list')), name='ad_update'),
    path('ad/<int:pk>/delete', views.AdDeleteView.as_view(success_url=reverse_lazy('ads:ad_list')), name='ad_delete'),

    # Milestone 2
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment', views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:ad_list')), name='ad_comment_delete'),

    # Milestone 3
    path('ad/<int:pk>/favorite', views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

autos/urls.py
from django.urls import path
from . import views

app_name = 'autos'
urlpatterns = [
    path('', views.IndexView.as_view(), name='auto_list'),
    path('create/', views.AutoCreate.as_view(), name='auto_create'),
    path('<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),
    path('<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),

    path('make/', views.MakeView.as_view(), name='make_list'),
    path('make/create/', views.MakeCreate.as_view(), name='make_create'),
    path('make/<int:pk>/update/', views.MakeUpdate.as_view(), name='make_update'),
    path('make/<int:pk>/delete/', views.MakeDelete.as_view(), name='make_delete')
]

cats/urls.py
from django.urls import path
from . import views

app_name = 'cats'
urlpatterns = [
    path('', views.IndexView.as_view(), name='cat_list'),
    path('create/', views.CatCreate.as_view(), name='cat_create'),
    path('<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),

    path('breed/', views.BreedView.as_view(), name='breed_list'),
    path('breed/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('breed/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('breed/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete')
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path
from django.views.static import serve
from django.contrib.auth import views as auth_views


# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    # Default paths
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),

    # My apps
    path('', include('home.urls')),
    path('hello', include('hello.urls')),
    path('polls/', include('polls.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('ads/', include('ads.urls')),

    # Serve the static HTML
    path(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
    # Serve the favicon
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    )
]

# Switch to social login if it is configured
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
        path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
    )
    print('Using', social_login, 'as the login template.')
except:
    print('Using registration/login.html as the login template.')

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.views import generic
from django.shortcuts import render

class HomeView(generic.TemplateView):
    template_name = 'home/main.html'

def home(request):
    return render(request, 'home/main.html')

home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

    <meta name="dj4e" content="2084ffc53b63cad1ad7737bd42edd393">
    <meta name="dj4e-code" content="42162764637354">
    <meta name="dj4e-version" content="2021-04-14">

    <link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
        crossorigin="anonymous"
    >
    <link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
        crossorigin="anonymous"
    >
    <link
        rel="stylesheet"
        href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
        crossorigin="anonymous"
    >

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

    {% block head %} {% endblock %}
</head>

<body>
    <div class="container">
        {% block navbar %} {% endblock %}
        {% block welcome %} {% endblock %}
        {% block messages %}
            {% if messages %}
                {% for msg in messages %}
                <div class="alert alert-{{msg.level_tag}}" role="alert">
                    {{msg.message}}
                </div>
                {% endfor %}
            {% endif %}
        {% endblock %}
        {% block content %}
        {% endblock %}
    </div>
    {% block footer %} {% endblock %}
</body>

</html>

home/templates/base_menu.html
{% extends "base_bootstrap.html" %}
{% block navbar %}
{% load app_tags %}

<nav class="navbar navbar-default navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
        </div>

        <ul class="nav navbar-nav">
            {% url 'ads:ad_list' as ads %}
            <li {% if request.get_full_path == ads %} class="active" {% endif %}>
                <a href="{% url 'ads:ad_list' %}">Ads</a>
            </li>
            {% url 'cats:cat_list' as cats %}
            <li {% if request.get_full_path == cats %} class="active" {% endif %}>
                <a href="{% url 'cats:cat_list' %}">Cats</a>
            </li>
            {% url 'autos:auto_list' as autos %}
            <li {% if request.get_full_path == autos %} class="active" {% endif %}>
                <a href="{% url 'autos:auto_list' %}">Autos</a>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'ads:ad_create' %}">Create Ad</a>
                </li>
                <li class="dropdown">
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                        <img style="width: 25px;" src="{{ user|gravatar:60 }}" /><b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'logout' %}?next={% url 'ads:ad_list' %}">Logout</a></li>
                    </ul>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'login' %}?next={% url 'ads:ad_list' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% endblock %}