ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.IndexView.as_view(), name='ad_list'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create', views.AdCreateView.as_view(success_url=reverse_lazy('ads:ad_list')), name='ad_create'),
    path('ad/<int:pk>/update', views.AdUpdateView.as_view(success_url=reverse_lazy('ads:ad_list')), name='ad_update'),
    path('ad/<int:pk>/delete', views.AdDeleteView.as_view(success_url=reverse_lazy('ads:ad_list')), name='ad_delete'),

    # Milestone 2
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment', views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:ad_list')), name='ad_comment_delete'),

    # Milestone 3
    path('ad/<int:pk>/favorite', views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path
from django.views.static import serve
from django.contrib.auth import views as auth_views


# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    # Default paths
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),

    # My apps
    path('', include('home.urls')),
    path('hello', include('hello.urls')),
    path('polls/', include('polls.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('ads/', include('ads.urls')),

    # Serve the static HTML
    path(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
    # Serve the favicon
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    )
]

# Switch to social login if it is configured
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
        path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
    )
    print('Using', social_login, 'as the login template.')
except:
    print('Using registration/login.html as the login template.')

ads/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
from taggit.managers import TaggableManager


class Ad(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, 'Title must be greater than 2 characters.')]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Milestone 2
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(
        max_length = 256,
        null = True,
        help_text = 'The MIME Type of the file.'
    )
    comments = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='Comment',
        related_name='comments_owned'
    )

    # Milestone 3
    favorites = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='Fav',
        related_name='favorite_ads'
    )

    # Milestone 4
    tags = TaggableManager(blank=True)

    # Shows up in the admin list
    def __str__(self):
        return self.title


class Comment(models.Model):
    text = models.TextField(
        validators=[MinLengthValidator(3, 'Comment must be greater than 3 characters.')]
    )
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15:
            return self.text
        return self.text[:11] + ' ...'


class Fav(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('ad', 'user')

    # Shows up in the admin list
    def __str__(self):
        return f'{self.user.username} likes {self.ad.title[:7]}'

ads/forms.py
from django import forms
from ads.models import Ad
from ads.humanize import naturalsize
from django.core.files.uploadedfile import InMemoryUploadedFile


class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(
        required = False,
        label = 'File to upload must be <= ' + max_upload_limit_text
    )
    upload_field_name = 'picture'

    class Meta:
        model = Ad
        fields = ['title', 'price', 'text', 'tags', 'picture']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be <= " + self.max_upload_limit_text + " bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture  # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
            self.save_m2m()

        return instance


class CommentForm(forms.Form):
    comment = forms.CharField(
        required=True,
        min_length=3,
        max_length=500,
        strip=True
    )

ads/views.py
from ads.models import Ad, Comment, Fav
from ads.owner import OwnerListView, OwnerDetailView, OwnerDeleteView
from ads.forms import CreateForm, CommentForm
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.http.response import HttpResponse


class IndexView(OwnerListView):
    model = Ad
    template_name = 'ads/ad_list.html'

    def get(self, request):
        favorites = list()

        if (request.user.is_authenticated):
            rows = request.user.favorite_ads.values('id')  # [{'id': 2}, {'id': 7}, ...]
            favorites = [row['id'] for row in rows]  # [2, 7, ...]

        # Milestone 4
        ad_search = request.GET.get("search", False)

        if (ad_search):
            query = Q(title__icontains=ad_search)
            query.add(Q(text__icontains=ad_search), Q.OR)
            query.add(Q(tags__name__in=[ad_search]), Q.OR)
            ad_list = Ad.objects.filter(query).select_related().distinct().order_by('-updated_at')[:10]
        else:
            ad_list = Ad.objects.all().order_by('-updated_at')

        ctx = {'ad_list': ad_list, 'search': ad_search ,'favorites': favorites}

        return render(request, self.template_name, ctx)


class AdDetailView(OwnerDetailView):
    model = Ad
    template_name = 'ads/ad_detail.html'

    def get(self, request, pk):
        comment_ad = Ad.objects.get(id=pk)
        comments = Comment.objects.filter(ad=comment_ad).order_by('-updated_at')
        comment_form = CommentForm()
        ctx = {'ad': comment_ad, 'comments': comments, 'comment_form': comment_form}

        return render(request, self.template_name, ctx)


class AdCreateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:ad_list')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}

        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        ad = form.save(commit=False)
        ad.owner = self.request.user
        ad.save()
        form.save_m2m()

        return redirect(self.success_url)


class AdUpdateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:ad_list')

    def get(self, request, pk):
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(instance=ad)
        ctx = {'form': form}

        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=ad)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        ad = form.save(commit=False)
        ad.save()
        form.save_m2m()

        return redirect(self.success_url)


class AdDeleteView(OwnerDeleteView):
    model = Ad


# Milestone 2

def stream_file(request, pk):
    ad = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = ad.content_type
    response['Content-Length'] = len(ad.picture)
    response.write(ad.picture)

    return response


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk):
        success_url = reverse_lazy('ads:ad_detail', args=[pk])
        ad = get_object_or_404(Ad, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, ad=ad)
        comment.save()

        return redirect(success_url)


class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = 'ads/comment_confirm_delete.html'


# Milestone 3

from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError

@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        fav_ad = get_object_or_404(Ad, id=pk)
        fav = Fav(user=request.user, ad=fav_ad)
        try:
            fav.save()
        except IntegrityError:
            pass

        return HttpResponse()

@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        del_ad = get_object_or_404(Ad, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, ad=del_ad)
            fav.delete()
        except Fav.DoesNotExist:
            pass

        return HttpResponse()

ads/templates/ads/ad_confirm_delete.html
{% extends "base_menu.html" %}

{% block content %}
    <h1>Delete Ad</h1>

    <p>Are you sure you want to delete the ad: {{ ad }}?</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
        <input
            type="submit"
            onclick="window.location='{% url 'ads:ad_list' %}'; return false;"
            value="Cancel"
        >
    </form>
{% endblock %}

ads/templates/ads/ad_detail.html
{% extends "base_menu.html" %}
{% load humanize %}

{% block head %}
    <style>
        .overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: 10;
            display: none;
            background-color: rgba(0, 0, 0, 0.5);
        }
        .overlay img {
            width: 50%;
            margin-top: 50px;
            border: 3px solid #000;
        }
        .ad-picture {
            float: right;
            max-width: 50%;
        }
        .ad-tags {
            color: white;
            border: 1px #000 solid;
            background-color: #1c55ff;
        }
    </style>
{% endblock %}

{% block content %}
    {% if ad.content_type %}
        <div
            id="overlay"
            class="overlay"
            style="text-align: center;"
            onclick="document.getElementById('overlay').style.display = 'none';"
        >
            <img src="{% url 'ads:ad_picture' ad.id %}">
        </div>
    {% endif %}

    <span style="float: right;">
        ({{ ad.updated_at|naturaltime }})
        {% if ad.owner == user %}
        <a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
        <a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
        {% endif %}
    </span>

    <h1>{{ ad.title }}</h1>
    {% if ad.content_type %}
        <img
            src="{% url 'ads:ad_picture' ad.id %}"
            class="ad-picture"
            onclick="document.getElementById('overlay').style.display = 'block';"
        >
    {% endif %}
    <p>
        {{ ad.text }}
    </p>
    <p>
       Price: {{ ad.price }}
    </p>

    {% if ad.tags.all %}
    <p>
        Tags:
        {% for tag in ad.tags.all %}
        <span class="ad-tags">{{ tag }}</span>
        {% endfor %}
    </p>
    {% endif %}

    <br clear="all"/>
    <!-- Ad Comments -->
    {% if user.is_authenticated %}
        {% load crispy_forms_tags %}
        <form action="{% url 'ads:ad_comment_create' ad.id %}" method="POST">
            {% csrf_token %}
            {{ comment_form|crispy }}
            <input type="submit" value="Submit">
        </form>
    {% endif %}
    {% for comment in comments %}
        <p>
        {{ comment.text }}
        ({{ comment.updated_at|naturaltime }})
        {% if user == comment.owner %}
            <a href="{% url 'ads:ad_comment_delete' comment.id %}">
                <i class="fa fa-trash"></i>
            </a>
        {% endif %}
        </p>
    {% endfor %}

    <br clear="all"/>
    <p>
        <a href="{% url 'ads:ad_list' %}">All ads</a>
    </p>
{% endblock %}

ads/templates/ads/ad_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <p>
    <form action="" method="post" id="upload_form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit">
        <input
            type="submit"
            onclick="window.location.href='{% url 'ads:ad_list' %}';return false;"
            value="Cancel"
        >
    </form>
    </p>
    <!-- Check upload file size -->
    <script>
    $("#upload_form").submit(function() {
        if (window.File && window.FileReader && window.FileList && window.Blob) {
            var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
            if (file && file.size > {{ form.max_upload_limit }}) {
                alert("File " + file.name + " must be <= {{ form.max_upload_limit_text }}")
            return false;
            }
        }
    });
    </script>
{% endblock %}

ads/templates/ads/ad_list.html
{% extends "base_menu.html" %}

{% block content %}
<h1>Ads</h1>

<div style="float: right;">
<form>
    <input
        type="text"
        placeholder="Search..."
        name="search"
        {% if search %} value="{{ search }}" {% endif %}
    >
    <button type="submit"><i class="fa fa-search"></i></button>
    <a href="{% url 'ads:ad_list' %}">
        <i class="fa fa-undo"></i>
    </a>
</form>
</div>

<p>
{% if ad_list %}
<ul>
    {% for ad in ad_list %}
    <li>
        <a href="{% url 'ads:ad_detail'  ad.id %}">{{ ad.title }}</a>
        {% if ad.owner == user %}
        (<a href="{% url 'ads:ad_update' ad.id %}">Edit</a> |
        <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>)
        {% endif %}

        <!-- Favorite and Unfavorite Ads -->
        {% if user.is_authenticated %}
        <a
            href="#"
            onclick="favPost('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }} ); return false;"
            {% if ad.id not in favorites %}
                style="display: none;"
            {% endif %}
            id="favorite_star_{{ad.id}}"
        >
            <span class="fa-stack" style="vertical-align: middle;">
                <i class="fa fa-star fa-stack-1x" style="color: gold;"></i>
                <i class="fa fa-star-o fa-stack-1x"></i>
            </span>
        </a>

        <a
            href="#"
            onclick="favPost('{% url 'ads:ad_favorite' ad.id %}', {{ ad.id }} ); return false;"
            {% if ad.id in favorites %}
                style="display: none;"
            {% endif %}
            id="unfavorite_star_{{ad.id}}"
        >
            <span class="fa-stack" style="vertical-align: middle;">
                <i class="fa fa-star fa-stack-1x" style="display: none; color: gold;"></i>
                <i class="fa fa-star-o fa-stack-1x"></i>
            </span>
        </a>
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% else %}
    <p>There are no ads in the database.</p>
{% endif %}
</p>

<p>
    <a href="{% url 'ads:ad_create' %}">Create Ad</a> |
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}?next={% url 'ads:ad_list' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}?next={% url 'ads:ad_list' %}">Login</a>
    {% endif %}
</p>

<script>
    function favPost(url, ad_id) {
        console.log('Requesting AJAX');
        $.post(url, {}, function(rows) {
            console.log(url, 'finished.');
            $("#unfavorite_star_" + ad_id).toggle();
            $("#favorite_star_" + ad_id).toggle();
        }).fail(function(xhr) {
            alert('Url failed with' + xhr.status);
        });
    }
</script>
{% endblock %}

ads/templates/ads/comment_confirm_delete.html
{% extends "base_menu.html" %}

{% block content %}
    <h1>Delete Comment</h1>

    <p>Are you sure you want to delete: {{ comment.text }}</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
        <input
            type="submit"
            onclick="window.location='{% url 'ads:ad_detail' comment.ad.id %}'; return false;"
            value="Cancel"
        >
    </form>
{% endblock %}